name: ci-cd

on: [push]

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - id: analyze
        uses: rotorsoft/semrel-analyze@v1
        with:
          package: 'chatbot'
          directory: 'chatbot'
          git-url: "${{ github.server_url }}/${{ github.repository }}"
          
      - name: analysis
        run: |
          echo "last-tag: ${{ steps.analyze.outputs.last-tag }}"
          echo "next-tag: ${{ steps.analyze.outputs.next-tag }}"
          echo "next-version: ${{ steps.analyze.outputs.next-version }}"
          echo "${{ steps.analyze.outputs.change-log }}"
